server.port=8080
# Si tu lances le backend depuis IntelliJ/Eclipse, il tape sur le port 5432 expos� par Docker
spring.datasource.url=jdbc:postgresql://localhost:5432/ibe_db
spring.datasource.username=ibe_user
spring.datasource.password=ibe_dev_pass

app.whatsapp.admin-number=237600000000
app.admin.username=admin
app.admin.password=admin

# Remplace par tes vraies cl�s de test Cloudinary plus tard
cloudinary.url=cloudinary://TEST_API_KEY:TEST_API_SECRET@TEST_CLOUD

app.cors.allowed-origins=http://localhost:4200
logging.level.com.example.institue1=DEBUG